apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- service.yaml
replicas:
- name: vote
  count: 2
images:
- name: schoolofdevops/vote
  newTag: v1
namespace: staging
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
