apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- service.yaml
replicas:
- name: vote
  count: 4
images:
- name: schoolofdevops/vote
  newTag: v1
namespace: prod
commonLabels:
  project: instavote
  env: prod
commonAnnotations:
  supported-by: "sre@example.com"
